### ISSUE TITLE
Feature Request: Add Listening to instead of Playing a Game like Spotify RPC has, and also add Play on button like Spotify RPC has, but make it so you can select what music streaming service or roon you want the play on button to use.

### ISSUE THREAD

**Issue by Cxsmo-ai** [jtpox/discord-presence-roon#3]
Feature Request: Add Listening to instead of Playing a Game like Spotify RPC has, and also add Play on button like Spotify RPC has, but make it so you can select what music streaming service or roon you want the play on button to use.

**Comment by jtpox** [comment]
Discord RPC does not have the ability to set the activity type unfortunately, so we're stuck with "Playing".

Refer: https://github.com/discordjs/RPC/issues/116

**Comment by Cxsmo-ai** [comment]
yes it does stuff like vencord discord custom rpc and stuff have the ability to do it 
![image](https://github.com/jtpox/discord-presence-roon/assets/74084396/4c8abc79-2e1b-4a87-84ea-0b8720ebaae9)

**Comment by jtpox** [comment]
Are mods even allowed under Discord's terms of service? If it isn't (which is most likely the answer), I will not add support for it.

**Comment by Cxsmo-ai** [comment]
https://discord.com/developers/docs/topics/rpc#setactivity

**Comment by Cxsmo-ai** [comment]
i wasn't talking about making it a mod i was just saying it is possible and there's a version of discord.js rpc that has it

**Comment by SerenModz21** [comment]
> yes it does stuff like vencord discord custom rpc and stuff have the ability to do it ![image](https://private-user-images.githubusercontent.com/74084396/267376601-4c8abc79-2e1b-4a87-84ea-0b8720ebaae9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3ODAzMTMsIm5iZiI6MTcwNzc4MDAxMywicGF0aCI6Ii83NDA4NDM5Ni8yNjczNzY2MDEtNGM4YWJjNzktMmUxYi00YTg3LTg0ZWEtMGI4NzIwZWJhYWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDIzMjAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYjhlZGQ0MmNhOGVmYmRmM2Q1Zjg4MDAyNGQ0ZDllOWE1MmYwZTY4YWQzNzEwZjliN2MyY2FjZDYxZDVmYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KOsofUTYWfPM8TmGkhZXeVKvJ5f9GWfcwh2hyktyDEo)

Hi! I came across this PR and just wanted to share that unfortuatently, Discord does not allow RPC's to change activity type. If you were to look at https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum and go just below the activity type table, Discord states the following: "_ActivityType is strictly for the purpose of handling events that you receive from Discord; though the SDK/our API will not reject a payload with an ActivityType sent, **it will be discarded and will not change anything in the client**._"

As for your mention of supporting such: it is only possible because they don't use Discord's API, rather they dispatch an event to webpack from what I can tell. This can be seen here: https://github.com/Vendicated/Vencord/blob/main/src/plugins/customRPC/index.tsx#L379-L383

Therefore, such is only possible to those how break the Discord TOS which is not recommended.
